### ISSUE TITLE
Repo is leaking git folder information

### ISSUE THREAD

**Issue by githubbbie** [contributoragreements/contributoragreements.org#8]
> OST: [contributoragreements.org](http://contributoragreements.org/)
> UUID: 0adf0c607b2
> Hello there,
> 
> Our security scanner [Repo Lookout](https://www.repo-lookout.org/) has found a likely vulnerability on a host for which you are listed as the contact!
> 
> Repo Lookout is a non-commercial project to find inadvertently publicly exposed source code repositories.
> 
> Details
> The following URL was world-readable at the time of scanning (Jul 9 '23):
> 
> https://contributoragreements.org/query2form/.git/logs/HEAD
> This allows (at least partial) access to the site's underlying source code repository!
> 
> For instance, the last 5 code commits have been:
> 
> 5315c460: added support for processurl
> d1896382: fixed configs
> 39f3c2d9: fixed forms
> cb3dbe12: more cleanup
> c46b904b: signer feature added
> Such access to the repository could give a malicious actor insight into the structure of the site (e.g. hidden functionality, critical bugs, or credentials to third-party services) and enable downstream attacks (e.g. data leakage, phishing, and extortion).
> 
> If this was not intended, we highly recommend to disable access to the source code repository!
> 
> Note that if the repository was intentionally made available, no action is required.
> 
> What is „Repo Lookout“?
> Repo Lookout is a large-scale security scanner, with a single purpose: Find source code repositories that have been inadvertently exposed to the public and report them to the domain’s technical contact.
> 
> Visit [www.repo-lookout.org](https://www.repo-lookout.org/) to learn more about the project.
> 
> Sponsoring
> If you found this vulnerability report useful, please consider supporting the project by becoming a sponsor on [Ko-fi](https://ko-fi.com/repolookout). Thank you very much!
> 
> 
> Best regards,
> The „Repo Lookout“ Team

Solution would be to hide all .git and/or all .* files and directories on the webserver.

**Comment by step21** [comment]
(closed, b/c repo is public anyway)
